<h1><center>Laboratorio 7: Aprendizaje Supervisado 🔮</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

### Cuerpo Docente:

- Profesor: Pablo Badilla
- Auxiliar: Ignacio Meza D.
- Ayudante: Patricio Ortiz

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Matías Vergara Silva
- Nombre de alumno 2:


### **Link de repositorio de GitHub:** `https://github.com/matiasvergaras/MDS7201`

## Temas a tratar

- Aprendizaje Supervisado
- Flujos de datos a través de `Pipelines`.

## Reglas

- Fecha de entrega: TBD
- **Grupos de 2 personas**
- **Ausentes** deberán realizar la actividad solos. 
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias. 
- Pueden usar cualquer matrial del curso que estimen conveniente.

## Objetivos principales del laboratorio

- Comprender el funcionamiento de clasificadores/regresores.
- Generar múltiples modelos predictivos.
- Comprender las ventajas de crear modelos en pipeline vs hacer las operaciones a mano.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre `DataFrames`.

### Importamos librerias utiles 😸

In [61]:
# Libreria Core del lab.
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split 

# Pre-procesamiento
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

# Clasificacion
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor


# Metricas de evaluación
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import r2_score


#Libreria para plotear
!pip install --upgrade plotly
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# UMAP
!pip install umap-learn

Requirement already up-to-date: plotly in /Users/matias/anaconda3/lib/python3.7/site-packages (5.8.2)
  Using cached https://files.pythonhosted.org/packages/1e/e1/5712270ab8749ff1fe4d3b8e9398cfaa51d1334caf60b6348f7619b1d6be/numba-0.55.2-cp37-cp37m-macosx_10_14_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/cd/b3/ef391866c48f594c3a710101c691a6346645d7d14d7c751b37cbaabcdd3d/llvmlite-0.38.1-cp37-cp37m-macosx_10_9_x86_64.whl
  Found existing installation: llvmlite 0.26.0
Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.


https://www.kaggle.com/antoinekrajnc/soccer-players-statistics

# 1. Predicciones Futboleras

<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1BnO4tyh3vM2P199Ec9s3JjngQ4qQ9seP"
" width="300">
</p>


Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones. 

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.


**Los Datos**

Para este laboratorio deberán trabajar con los csv `statsplayers.csv` y `salarios.pickle`, donde deberán aplicar algoritmos de de aprendizaje supervisado (clasificación y regresión) en base a características que describen de jugadores de futbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [ ]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = 'Dirección donde tiene los archivos en el Drive'
except: 
    print('Ignorando conexión drive-colab')

Ignorando conexión drive-colab


In [2]:
df_players = pd.read_csv('stats_players.csv')
df_players

Name          Nationality National_Position  \
0       Cristiano Ronaldo             Portugal                LS   
1            Lionel Messi            Argentina                RW   
2                  Neymar               Brazil                LW   
3             Luis Suárez              Uruguay                LS   
4            Manuel Neuer              Germany                GK   
5                  De Gea                Spain                GK   
6      Robert Lewandowski               Poland                LS   
7             Gareth Bale                Wales                RS   
8      Zlatan Ibrahimović               Sweden               NaN   
9        Thibaut Courtois              Belgium                GK   
10         Jérôme Boateng              Germany               RCB   
11            Eden Hazard              Belgium                LF   
12            Luka Modrić              Croatia               NaN   
13             Mesut Özil              Germany               CAM   
14        Gonzalo Higuaín            Argentina               Sub   
15           Thiago Silva               Brazil               Sub   
16           Sergio Ramos                Spain               LCB   
17          Sergio Agüero            Argentina               Sub   
18             Paul Pogba               France               NaN   
19      Antoine Griezmann               France               CAM   
20        Kevin De Bruyne              Belgium               RCM   
21             Marco Reus              Germany               NaN   
22         Alexis Sánchez                Chile                LW   
23             Toni Kroos              Germany               LDM   
24            Diego Godín              Uruguay               LCB   
25           Mats Hummels              Germany               LCB   
26            Hugo Lloris               France                GK   
27      Giorgio Chiellini                Italy               LCB   
28           Philipp Lahm              Germany               NaN   
29                   Pepe             Portugal               RCB   
...                   ...                  ...               ...   
17558       Kieran Butler  Republic of Ireland               NaN   
17559           Kyle Egan              England               NaN   
17560       Alfie Kilgour              England               NaN   
17561        Shane Hanney  Republic of Ireland               NaN   
17562         Louis Jones              England               NaN   
17563           Ben Kelly  Republic of Ireland               NaN   
17564        Kaylen Hinds              England               NaN   
17565          James King              England               NaN   
17566     Neil McLaughlin             Scotland               NaN   
17567     Nathan Clifford  Republic of Ireland               NaN   
17568        Ciaran Kelly  Republic of Ireland               NaN   
17569         Adam Kelsey              England               NaN   
17570     Dominic Peppard  Republic of Ireland               NaN   
17571       Gavin Dowling  Republic of Ireland               NaN   
17572     Tommy Käßemodel              Germany               NaN   
17573        Ronan Wilson     Northern Ireland               NaN   
17574     Darragh Doherty  Republic of Ireland               NaN   
17575          Myles Judd              England               NaN   
17576          Sam Hornby              England               NaN   
17577        Sam Sargeant              England               NaN   
17578       Steven Alzate              England               NaN   
17579           Sam Dalby              England               NaN   
17580       Henry Ochieng              England               NaN   
17581       Harry Clifton              England               NaN   
17582     Mark McElhinney  Republic of Ireland               NaN   
17583         Adam Dunbar  Republic of Ireland               NaN   
17584        Dylan McGoey  Republic of Ireland               NaN   
17585    

## 1.1 Predicción de Seleccionados Nacionales 

Como primera tarea, Renacín, intrigado por la posibilidad de saber qué tan reconocido es un jugador, le consulta a su equipo si es posible predecir si un jugador será o no seleccionado nacional a partir de sus estadísticas en el juego. 

<p align="center">
  <img src="https://thumbs.gfycat.com/ThornyFrankFoxhound-size_restricted.gif" width="500">
</p>

### 1.1.1 Generación de Labels para la Clasificación [Sin Puntaje]


Primero comience generando las labels para la clasificación. Para esto, trabaje sobre el atributo ```National_Position``` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. 

Hecho esto, ¿Cuantos ejemplos por cada clase se tienen? Comente lo que observa.



**Respuesta:**

In [36]:
no_nominados = df_players.loc[(df_players['National_Position'].isna())]
nominados = df_players.loc[~(df_players['National_Position'].isna())]

print(f"Jugadores no seleccionados: {no_nominados.shape[0]}")
print(f"Jugadores seleccionados: {nominados.shape[0]}")
print(f"Porcentaje seleccionados: {round(nominados.size/(df_players.size) * 100, 2)}%")

# para que los labels queden en el dataset
df_players.loc[(df_players['National_Position'].isna()),'Seleccionado'] = 0
df_players.loc[~(df_players['National_Position'].isna()),'Seleccionado'] = 1

Jugadores no seleccionados: 16513
Jugadores seleccionados: 1075
Porcentaje seleccionados: 6.11%


Se observa que solo una fracción mínima de los jugadores es seleccionada para jugar en sus naciones, representando solo un 6.11% del total de los datos. Lo anterior representa un desafío para la clasificación, en cuanto nos habla de un dataset con un target a predecir sumamente desbalanceado. Esto deberá ser tratado, pues de lo contrario podría inducir error en la clasificación.

### 1.1.2 Camino a la clasificación [1 punto]

<p align="center">
  <img src="https://c.tenor.com/SoXZJHWnhKAAAAAC/pitbull-medel.gif" width="500">
</p>

Para preprocesar el dataset, genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guardelo en algúna variable.

Luego, comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material ```Player_Stats_Report.html``` que viene en el zip del lab), al igual que las transformaciones aplicadas.

Hecho lo anterior, **defina al menos 3 pipelines para la clasificación**, en donde utilice el mismo ColumnTransformer definido anteriormente, pero que varie entre cada pipeline los clasificadores. 

Para seleccionar los clasificadores más adecuados, utilice la siguiente guía:

<p align="center">
  <img src="https://scikit-learn.org/stable/_static/ml_map.png" width="500">
</p>

<br/>

Con ella, comente y justifique cada una de las decisiones tomadas al momento de desarrollar su pipeline.

**Nota:** Si tiene problemas al utilizar OneHotEncoder puede utilizar el parámetro handle_unknown='ignore'. Esto hace que en la codificación se omitan las categorias que no aparecen en el entrenamiento. Pregunta dudosa (no tiene puntaje), ¿esto tiene sentido a nivel de modelos?.

**To-Do:**

- [ ] Genere un ```ColumnTransformer``` enfocado en preprocesar los datos.
- [ ] Indicar y Justificar que preprocesamiento utiliza sobre cada columna.
- [ ] Crear 3 ``pipelines`` con diferentes clasificadores.
- [ ] Para seleccionar los clasificadores base sus decisiones en la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)
- [ ] No entrenar los ``pipelines`` aún.

**Nota:** No es necesario entrenar los clasificadores aún.

**Respuesta:**

In [18]:
### Código aquí ###
preprocessingCT = ColumnTransformer(
    transformers=[
        ("StandardScaler",
         StandardScaler(),
            [
                "Weight",
                "Height",
                "Aggression",
                "Reactions",
                "Vision",
                "Composure",
                "Acceleration",
                "Speed",
                "Balance",
                "Strength",
                "Agility",
                "Jumping",
                "Finishing",
                "Volleys",
                "Penalties"
            ],
        ),
        ("OneHotEncoder",
         OneHotEncoder(drop='first', handle_unknown='ignore'),
            [
                "Club_Position",
                'Nationality',
                "Preffered_Foot",
                "Skill_Moves",
                "Work_Rate",
                "Weak_foot"
            ],
        ),
        ("MinMaxScaler",
         MinMaxScaler(),
            [
                "Ball_Control",
                "Dribbling",
                "Marking",
                "Sliding_Tackle",
                "Standing_Tackle",
                "Interceptions",
                "Crossing",
                "Short_Pass",
                "Long_Pass",
                "Stamina",
                "Heading",
                "Shot_Power",
                "Curve",
                "Freekick_Accuracy",
                "Long_Shots"
            ],
        ),
    ]
)


linear_svc_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT),
        ("classification", SVC(kernel="linear")),
    ]
)

knn_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", KNeighborsClassifier())]
)

svc_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", SVC(kernel="rbf"))]
)

El relación al preprocesamiento a aplicar en cada columna mediante ColumnTransformer, se escoge utilizar OneHotEncoder/StandardScaler/MinMaxScaler según el tipo de dato con el que se esté tratando y su distribución. De esta manera, atributos categóricos se tratan mediante OneHotEncoder, atributos numéricos de distribución normal con StandardScaler y numéricos con otra distribución distinta de la normal mediante MinMaxScaler. Este análisis fue posible gracias al summary entregado, que permite obtener la información necesaria para dichas decisiones de manera rápida.

Por otro lado, la elección de los 3 clasificadores solicitados (uno por cada pipeline) se basa en el "algorithm cheat-sheet" proporcionado, en donde se siguió la ruta de predecir una categoría (en nuestro caso, binaria) a partir de datos etiquetados donde se cuenta con menos de 100k ejemplos. Se toman los 3 clasificadores más razonables para este caso: Linear SVC, el recomendado, KNN, en caso de que este no funcione (y en vista de que nuestros datos no corresponden a texto), y RBF SVC como última alternativa.


### 1.1.3 Entrenemos los pipelines [1 punto]

<p align="center">
  <img src="https://i.gifer.com/7Cc8.gif" width="350">
</p>


Ahora, entrene los `pipeline` generados en los pasos anteriores. Para esto, primero separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio).

En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`).


Luego, entrene los pipelines

Una vez entrenado su modelo, evalue su rendimiento a través de diferentes métricas, comentando que significa cada uno de los valores obtenidos. Puede usar la función `classification_report` para corroborar sus resultados.

- ¿Qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional)?
- ¿Podrían mejorarse los resultados?, ¿Cómo?
- ¿Influye la cantidad de ejemplos por clase?

**To-Do**:

- [ ] Separar el conjunto de datos en entrenamiento y de prueba.
- [ ] Entrenar los `pipelines`.
- [ ] Utilizar las métricas para evaluar los modelos generados.


**Respuesta:**

In [44]:
### Código aquí ###
preprocessingCT = ColumnTransformer(
    transformers=[
        ("StandardScaler",
         StandardScaler(),
            [
                "Weight",
                "Height",
                "Aggression",
                "Reactions",
                "Vision",
                "Composure",
                "Acceleration",
                "Speed",
                "Balance",
                "Strength",
                "Agility",
                "Jumping",
                "Finishing",
                "Volleys",
                "Penalties"
            ],
        ),
        ("OneHotEncoder",
         OneHotEncoder(drop='first', handle_unknown='ignore'),
            [
                "Club_Position",
                'Nationality',
                "Preffered_Foot",
                "Skill_Moves",
                "Work_Rate",
                "Weak_foot"
            ],
        ),
        ("MinMaxScaler",
         MinMaxScaler(),
            [
                "Ball_Control",
                "Dribbling",
                "Marking",
                "Sliding_Tackle",
                "Standing_Tackle",
                "Interceptions",
                "Crossing",
                "Short_Pass",
                "Long_Pass",
                "Stamina",
                "Heading",
                "Shot_Power",
                "Curve",
                "Freekick_Accuracy",
                "Long_Shots"
            ],
        ),
    ]
)


linear_svc_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT),
        ("classification", SVC(kernel="linear")),
    ]
)

knn_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", KNeighborsClassifier())]
)

svc_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", SVC(kernel="rbf"))]
)

In [20]:
X = df_players.drop(["Name", "National_Position", "Seleccionado"], axis=1)
y = df_players["Seleccionado"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=Y)

linear_svc = linear_svc_pipe.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print('Resultados Linear SVC:')
print(classification_report(y_pred, y_test))
print("-"*50)

rbf_svc = svc_pipe.fit(X_train, y_train)
y_pred = rbf_svc.predict(X_test)
print('Resultados RBF SVC')
print(classification_report(y_pred, y_test))
print("-"*50)

knn = knn_pipe.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print('Resultados KNN')
print(classification_report(y_pred, y_test))

/Users/matias/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Resultados Linear SVC:
              precision    recall  f1-score   support

         0.0       1.00      0.95      0.97      5177
         1.0       0.24      0.78      0.37       100

    accuracy                           0.95      5277
   macro avg       0.62      0.87      0.67      5277
weighted avg       0.98      0.95      0.96      5277

--------------------------------------------------


/Users/matias/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Resultados RBF SVC
              precision    recall  f1-score   support

         0.0       1.00      0.94      0.97      5272
         1.0       0.01      0.80      0.02         5

    accuracy                           0.94      5277
   macro avg       0.51      0.87      0.50      5277
weighted avg       1.00      0.94      0.97      5277

--------------------------------------------------


/Users/matias/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Resultados KNN
              precision    recall  f1-score   support

         0.0       0.99      0.94      0.97      5229
         1.0       0.07      0.44      0.11        48

    accuracy                           0.94      5277
   macro avg       0.53      0.69      0.54      5277
weighted avg       0.99      0.94      0.96      5277



**Respuesta**:

```
Responderemos por separado a cada pregunta.

¿Qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional)?
> Accuracy: qué porcentaje de los jugadores fueron predichos de forma correcta, ya sea como seleccionados o como no seleccionados. Los tres clasificadores presentan un valor alto (sobre 0.90).
> Recall: qué porcentaje de los jugadores de la clase X fueron predichos correctamente. Esta métrica nos indica qué tan bien estamos "cubriendo" la clase X sin importar el error por falso positivo. En general, el caso de jugadores no seleccionados se cubre bastante bien (recall 0.94) mientras que el caso seleccionados varia entre 0.44 y 0.80.
> Precision: qué porcentaje de los jugadores predichos como X clase pertenecen realmente a X. Para los tres clasificadores, esta métrica es "muy buena" para la clase negativa y "muy mala" para la clase positiva (alcanzando en el mejor caso un 0.24 a través de linear SVC).

Estos resultados podrían parecer buenos, en cuanto algunas métricas resultan bastante elevadas. Esconden, sin embargo, un enorme engaño: dada la baja cantidad de seleccionados en los datos (y que el sampleo se realizó de forma estratificada), es muy fácil para los clasificadores "ganar" buenas métricas respondiendo siempre con la clase negativa, lo cual da lugar a los precision bajísimos antes mencionados. Es así como, en el fondo, los resultados son bastante malos, en cuanto los clasificadores podrían no ser capaces de captar jugadores seleccionados tras haber aprendido que es más importante el caso contrario (por su presencia en los datos).

¿Podrían mejorarse los resultados?, ¿Cómo?
> Si, los resultados podrían mejorarse de muchas maneras, en especial en lo que respecta al tratamiento del desbalance. Podrían aplicarse, por ejemplo, subsampling (sobre la clase sobrerepresentada) o oversampling (sobre la clase infrarepresentada), una combinación de ambos, o incluso técnicas más complejas (tales como la asignación de pesos para el entrenamiento). 

¿Influye la cantidad de ejemplos por clase?
> Sí, la cantidad de ejemplos por clase es un factor crucial en el aprendizaje supervisado y por ende en los resultados. Las razones ya fueron expuestas en las respuestas anteriores.
```

## 1.2 Predicción de posiciones de jugadores [2 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="500">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas. 

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características. 

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo ```Club_Position```, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF'] 
central_ataque = ['RW', 'CAM', 'LW'] 
central = ['RM', 'CM', 'LM'] 
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

Cabe señalar que al igual como lo realizado con la clasificación binaria, deberá justificar en base a la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) la elección del clasificador y se deben comentar los resultados obtenidos en la clasificación.

**Nota:** Clasifique solamente con las clases señaladas, si observa mas clases eliminelas de la clasficación.

**To-Do**:

- [ ] Aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección.
- [ ] Cuente cuantos por clase quedan.
- [ ] Entrene el nuevo pipeline y ejecute una evaluación de este.  
- [ ] Comente los resultados obtenidos.

**Respuesta:**

In [41]:
position_dict = {
    "ST": "ataque",
    "CF": "ataque",
    "RW": "central_ataque",
    "CAM": "central_ataque",
    "LW": "central_ataque",
    "RM": "central",
    "CM": "central",
    "LM": "central",
    "RWB": "central_defensa",
    "CDM": "central_defensa",
    "LWB": "central_defensa",
    "RB": "defensa",
    "CB": "defensa",
    "LB": "defensa",
    "GK": "arquero",
}

df_positions = df_players.copy()
df_positions["Position"] = df_positions["Club_Position"].map(position_dict).astype('category')
count = df_positions.groupby("Position").size().reset_index().rename({0: "Count"}, axis=1)

display(count)

print(f"Se tienen {count['Count'].sum()} ejemplos etiquetados apropiadamente.")
df_positions = (df_positions
                .dropna(subset=['Position']) # eliminar los que no caigan en alguna categoria de las entregadas
                .drop(['National_Position', 'Club_Position', 'Seleccionado'], axis = 1)
                # eliminar tambien las columnas innecesarias tras el mapeo de posiciones
               )

Position  Count
0          arquero    632
1           ataque    430
2          central    907
3   central_ataque    581
4  central_defensa    209
5          defensa   1180

Se tienen 3939 ejemplos etiquetados apropiadamente.


La tabla nos entrega la cantidad de ejemplos por posición en el dataset, donde nuevamente se evidencia un importante desbalance de clases (por ejemplo, la clase menos representada corresponde a central_defensa con solo 209 ejemplos, lo cual es menos de la cuarta parte de la clase más representada, central). Llama además la atención el hecho de que, en total, ahora se cuenta con tan solo 3939 ejemplos, a diferencia de los casi 18k del desafío anterior. Esto revela que la gran mayoría de los jugadores en estudio caía en alguna de las posiciones que no fueron incluidas en el mapeo.

In [45]:
### Código aquí ###
preprocessingCT = ColumnTransformer(
    transformers=[
        ("StandardScaler",
         StandardScaler(),
            [
                "Weight",
                "Height",
                "Aggression",
                "Reactions",
                "Vision",
                "Composure",
                "Acceleration",
                "Speed",
                "Balance",
                "Strength",
                "Agility",
                "Jumping",
                "Finishing",
                "Volleys",
                "Penalties"
            ],
        ),
        ("OneHotEncoder",
         OneHotEncoder(drop='first', handle_unknown='ignore'),
            [
               # "Club_Position", # solo cambia esta linea
                'Nationality',
                "Preffered_Foot",
                "Skill_Moves",
                "Work_Rate",
                "Weak_foot"
            ],
        ),
        ("MinMaxScaler",
         MinMaxScaler(),
            [
                "Ball_Control",
                "Dribbling",
                "Marking",
                "Sliding_Tackle",
                "Standing_Tackle",
                "Interceptions",
                "Crossing",
                "Short_Pass",
                "Long_Pass",
                "Stamina",
                "Heading",
                "Shot_Power",
                "Curve",
                "Freekick_Accuracy",
                "Long_Shots"
            ],
        ),
    ]
)


linear_svc_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT),
        ("classification", SVC(kernel="linear")),
    ]
)

knn_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", KNeighborsClassifier())]
)

svc_pipe = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", SVC(kernel="rbf"))]
)

In [46]:
linear_svc_pos = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", SVC(kernel="linear"))
    ]
)

svc_pos = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", SVC(kernel="rbf"))
    ]
)

knn_pos = Pipeline(
    [
        ("preprocessing", preprocessingCT), 
        ("classification", KNeighborsClassifier())
    ]
)

In [47]:
y = df_positions.loc[:,"Position"]
X = df_positions.drop(["Name", "Position"], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

linear_svc = linear_svc_pos.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print('Resultados Linear SVC:')
print(classification_report(y_pred, y_test))
print("-"*50)

rbf_svc = svc_pos.fit(X_train, y_train)
y_pred = rbf_svc.predict(X_test)
print('Resultados RBF SVC')
print(classification_report(y_pred, y_test))
print("-"*50)

knn = knn_pos.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print('Resultados KNN')
print(classification_report(y_pred, y_test))

/Users/matias/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Resultados Linear SVC:
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       190
         ataque       0.82      0.75      0.79       141
        central       0.69      0.59      0.64       319
 central_ataque       0.34      0.59      0.43       100
central_defensa       0.17      0.46      0.25        24
        defensa       0.95      0.82      0.88       408

       accuracy                           0.75      1182
      macro avg       0.66      0.70      0.66      1182
   weighted avg       0.81      0.75      0.77      1182

--------------------------------------------------


/Users/matias/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Resultados RBF SVC
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       190
         ataque       0.85      0.77      0.81       143
        central       0.70      0.54      0.61       349
 central_ataque       0.20      0.49      0.29        71
central_defensa       0.13      0.53      0.21        15
        defensa       0.95      0.82      0.88       414

       accuracy                           0.74      1182
      macro avg       0.64      0.69      0.63      1182
   weighted avg       0.82      0.74      0.77      1182

--------------------------------------------------


/Users/matias/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Resultados KNN
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       190
         ataque       0.71      0.68      0.69       136
        central       0.56      0.48      0.52       322
 central_ataque       0.26      0.40      0.32       114
central_defensa       0.16      0.30      0.21        33
        defensa       0.86      0.79      0.83       387

       accuracy                           0.67      1182
      macro avg       0.59      0.61      0.59      1182
   weighted avg       0.71      0.67      0.69      1182



**Respuesta**:

```
Nuevamente, se utiliza la guía para escoger los clasificadores, cayendo sin embargo en la misma selección (mas ahora encontrandonos ante un problema de clasificación multiclase en lugar de clasificación binaria). 


Con respecto a los resultados, se observa que en general los modelos tienen un excelente comportamiento para clases tales como arquero (con métricas perfectas en los 3 clasificadores), defensa y ataque, y un comportamiento menos favorable para las clase central, central_ataque y central_defensa. Este resultado coincide con el anterior en cuanto las clases con peores predicciones son aquellas con menor representación en los datos, fenómeno transversal a los 3 clasificadores.

Por otro lado, se observa también que el clasificador con los mejores resultados a nivel macro es linear SVC, con mejores resultados en todas las métricas en estudio. 

Finalmente, en lo que respecta a cómo se podrían mejorar los resultados, la respuesta se mantiene: lo primero y más urgente sería tratar el desbalance mediante alguna de las técnicas ya mencionadas. Posteriormente se podría hacer un ajuste de hiperparámetros, lo cual sería posible por ejemplo mediante Grid Search. Para ello sería sin embargo necesario (o al menos, recomendable) contar con un conjunto de validación ajeno al conjunto de test.
```

## 1.3 Predicción de Sueldos [2 puntos]

<p align="center">
  <img src="https://media.giphy.com/media/3oEjHWtHAFcOKS4iA0/giphy.gif" width="460">
</p>

Queriendo ahondar aún más en el mercado del balompíe, Renacin, logra obtener (de una manera no muy formal) los sueldos de múltiples futbolistas y los guarda en el archivo ```sueldos.csv```. Con ellos les solicita que generen un regresor que les permita predecir el sueldo de los futbolistas en base a las características de los pichichis, esto, debido a su motivación por invertir y/o realizar especulación sobre los sueldos de jugadores.

Renacin es claro señalando que deben seguir utilizando la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y comenten cada uno de los pasos realizados, para obtener su regresión lineal. Señalándoles que no aceptara un $R^2$ inferior a 0.35 para el modelo solicitado.

Para esta parte usted tiene total libertad en la generación del regresor, la unica exigencia es que utilice un pipeline para generar la regresión y utilice la metrica $R^2$ para medir el rendimiento de esta.

**To-Do**:

- [ ] Explique en que consiste la métrica $R^2$
- [ ] Generar un pipeline para la regresión.
- [ ] Obtener un regresor con un $R^2$ superior a  $0.35$.
- [ ] Comente sus resultados y si es posible mejorar los resultados obtenidos. ¿Se necesitarían más datos o otros tipos de características o una combinación de ambos?

**Respuesta**

In [50]:
df_salary = pd.read_csv('salarios.csv')
df_salary = df_salary.loc[:,['Player', 'Weekly Salary']]
df_wage = df_players.merge(df_salary, right_on='Player', left_on='Name', how='inner')
df_wage['Weekly Salary'] = df_wage['Weekly Salary'].astype(int)

In [51]:
wageCT = ColumnTransformer(
    transformers=[
        (
            "OneHotEncoder",
            OneHotEncoder(drop='first', handle_unknown='ignore'),
            [
                'Nationality',
                "Preffered_Foot",
                "Skill_Moves",
                "Work_Rate",
                "Weak_foot",
                'Club_Position'
            ],
        ),
        (
            "StandardScaler",
            StandardScaler(),
            [
                "Weight",
                "Height",
                'Age',
                "Aggression",
                "Reactions",
                "Vision",
                "Composure",
                "Acceleration",
                "Speed",
                "Balance",
                "Strength",
                "Agility",
                "Jumping",
                "Finishing",
                "Volleys",
                "Penalties"
            ],
        ),
        (
            "MinMaxScaler",
            MinMaxScaler(),
            [
                "Ball_Control",
                "Dribbling",
                "Marking",
                "Sliding_Tackle",
                "Standing_Tackle",
                "Interceptions",
                "Crossing",
                "Short_Pass",
                "Long_Pass",
                "Stamina",
                "Heading",
                "Shot_Power",
                "Curve",
                "Freekick_Accuracy",
                "Long_Shots"
            ],
        ),
    ]
)


wage_pipe = Pipeline(
    [
        ("preprocessing", wageCT),
        ("classification", RandomForestRegressor()),
    ]
)

In [66]:
y = df_wage.loc[:, "Weekly Salary"]
X = df_wage.drop(['Player', 'Weekly Salary', 'Name', 'Seleccionado'], axis=1)

display(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

pipe = wage_pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

print(f"R^2: {round(r2_score(y_test, y_pred), 3)}")


Nationality National_Position Club_Position  Height  Weight  \
0                Portugal                LS            LW     185      80   
1               Argentina                RW            RW     170      72   
2                  Brazil                LW            LW     174      68   
3                 Uruguay                LS            ST     182      85   
4                 Germany                GK            GK     193      92   
5                  Poland                LS            ST     185      79   
6                   Wales                RS            RW     183      74   
7                 Belgium                GK            GK     199      91   
8                 Germany               RCB           Sub     192      90   
9                 Belgium                LF            LW     173      74   
10                Germany               CAM           CAM     180      76   
11              Argentina               Sub            ST     184      92   
12                 Brazil               Sub           LCB     183      79   
13                  Spain               LCB           LCB     183      75   
14              Argentina               Sub            ST     173      70   
15                 France               NaN           LCM     191      84   
16                 France               CAM            RS     176      67   
17                Belgium               RCM           RCM     181      68   
18                Germany               NaN            LW     182      76   
19                  Chile                LW            ST     169      62   
20                Germany               LDM           LCM     182      78   
21                Uruguay               LCB           LCB     185      73   
22                Germany               LCB           LCB     191      92   
23                 France                GK            GK     188      82   
24                  Italy               LCB           LCB     187      84   
25                  Italy                GK            GK     192      91   
26               Slovenia                GK            GK     189      87   
27               Colombia               LAM           CAM     180      75   
28                  Gabon               NaN            ST     187      80   
29                  Italy                CB           RCB     190      85   
...                   ...               ...           ...     ...     ...   
1836               Sweden               NaN            GK     194      84   
1837        United States               NaN           Res     175      68   
1838               Sweden               NaN           Sub     189      83   
1839              England               NaN           Res     176      74   
1840              England               NaN           Res     166      62   
1841              Germany               NaN           Res     167      48   
1842  Republic of Ireland               NaN           Res     185      80   
1843              England               NaN           Res     191      75   
1844               France               NaN           Sub     193      88   
1845        United States               NaN           Sub     175      64   
1846               France               NaN           Res     185      83   
1847              England               NaN           Res     180      76   
1848               France               NaN           Res     190      81   
1849               France               NaN           Res     164      60   
1850                Italy               NaN           Res     186      82   
1851               France               NaN           Res     183      68   
1852               France               NaN           Res     180      70   
1853              England               NaN           Sub     190      82   
1854          Switzerland               NaN           Res     193      90   
1855              Denmark               NaN           Res     188      77   
1856      

R^2: 0.614


/Users/matias/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


**Respuestas**:

- La guía ahora nos posiciona al otro lado de la figura, en el caso donde lo que se busca predecir es una cantidad. Siguiendo la ruta y decidiendonos por la opción en donde muchas variables son importantes para el resultado, nos encontramos con que una buena opción de clasificador son aquellos de la familia de Ensemble Regressors. Siguiendo este consejo, se opta por utilizar Random Forest como clasificador. 

- La métrica $R^2$ corresponde a un coeficiente que indica la proporción de la varianza explicada por el modelo, es decir, captura el "qué tan bien" se explica el comportamiento de la variable dependiente (en este caso, el sueldo) en base a las variables independientes (la información de los jugadores que se le quiera dar al clasificador).

- En cuanto a los resultados obtenidos, se observa un R2 de 0.614, es decir, el 61.4% de la variación de la variable independiente (sueldo semanal de los jugadores) se explica por las variables independientes (en este caso, toda la información inicial del conjunto de datos). Este resultado es favorable, mas perfectible. Aún existe más de 1/4 de la variación sin explicar, lo cual de disminuir aumentaría la confiabilidad del regresor.

- En cuanto a formas de mejorar los resultados, las dos opciones propuestas sirven: tanto el agregar más datos como el agregar características adicionales. Mientras los datos nuevos sirven de ejemplo para potenciar el aprendizaje del clasificador, las características adicionales pueden permitir alcanzar una mayor explicación de la variación (un mayor R2) contribuyendo así también a la obtención de mejores predicciones. 

# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media2.giphy.com/media/l1J3CbFgn5o7DGRuE/giphy.gif">
</p>

<br>
<center>
<img src="https://i.kym-cdn.com/photos/images/original/001/194/195/b18.png" width=100 height=50 />
</center>
<br>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>